### 3. 파이토치 텐서 생성

In [1]:
import torch

# 이차원 리스트로 실수형 텐서 생성
print(len(x.size()))

tensor([[1., 2.],
        [3., 4.]])

In [3]:
lt = torch.LongTensor([[1, 2], [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [4]:
bt = torch.ByteTensor([[1, 2], [3, 4]])
bt

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [ ]:
# 텐서의 크기를 주고 임의의 값으로 채움
x = torch.FloatTensor(3, 2) # 3행 2열 데이터 생성
x #값을 넣지 않았기 때문에 쓰레기값 생성

### 4. 넘파이 호환

In [5]:
import numpy as np

x = np.array([[1, 2],
              [3, 4]])  # Define numpy array.
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [6]:
x

array([[1, 2],
       [3, 4]])

In [7]:
# 넘파이의 ndarray를 파이토치의 텐서로 변환
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [8]:
# 텐서를 ndarray로 변환
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


### 5. 텐서 타입 변환

In [10]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [11]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

### 6. 텐서 크기 구하기

In [13]:
# 3 x 2 x 2 텐서 x 선언
x = torch.FloatTensor([[[1,2], [3,4]],[[5, 6],[7,8]],[[9, 10], [11, 12]]])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [15]:
y = np.arange(1,13).reshape(3,2,2)
x = torch.from_numpy(y).float()
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [16]:
print(x.size()) # 크기 메소드
print(x.shape) # 크기 속성

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [18]:
# print(y.size()) numpy에는 size() 메서드 없음
print(y.shape) # numpy의 shape은 튜플 형태

(3, 2, 2)


In [19]:
print(x.size(1))
print(x.shape[1])

2
2


In [20]:
print(x.dim())
print(len(x.size()))

3
3


## 기본 연산

### 1. 요소별 산술 연산

In [22]:
a = torch.FloatTensor([[1, 2], [3, 4]])
b = torch.FloatTensor([[2, 2], [3, 3]])
a + b

tensor([[3., 4.],
        [6., 7.]])

### 2. 인플레이스 연산(in-place) 연산
- 함수명 다음에 밑줄이 붙음
- 연산한 결과가 새로운 메모리에 할당되지 않고 원래 변수(텐서)에 할당 

In [23]:
a = torch.FloatTensor([[1, 2], [3, 4]])
b = torch.FloatTensor([[2, 2], [3, 3]])
a.mul(b)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


tensor([[ 2.,  4.],
        [ 9., 12.]])

In [24]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [25]:
a.mul_(b)

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [26]:
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])


참고: 연산 전후의 데이터 타입이 달라지면 오류가 발생

In [27]:
a = torch.LongTensor([[1, 2], [3, 4]])
b = torch.FloatTensor([[2, 2], [3, 3]]) 
a.mul_(b) # a에 실수를 넣으려고 하면 에러 발생

RuntimeError: result type Float can't be cast to the desired output type Long

In [28]:
b.mul_(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])

(실수 x 정수) 연산은 결과가 실수가 되므로 원래 실수인 b의 메서드를 사용하면 문제가 발생하지 않는다.

### 3. 차원 축소 연산
벡터(1차원 배열)의 합은 스칼라 값이므로 차원이 하나 줄어들게 됨

In [35]:
x.data_ptr() == y.data_ptr()

In [36]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [37]:
print(x.sum(dim=0))

tensor([4., 6.])


### 4. 브로드캐스팅 연산
크기가 다른 텐서들의 산술 연산을 가능하게 함
- 텐서 + 스칼라
- 텐서 + 벡터
- 텐서 + 텐서

규칙
- 규칙 1: 두 배열의 차원 수가 다르면 작은 차원을 가진 배열의 앞쪽을 1로 채운다.
- 규칙 2: 두 배열의 shape이 일치하지 않는다면, 일치하지 않는 차원에서 크기가 1인 다른쪽 배열의 크기와 일치하도록 수정한다.
- 규칙 3: 임의의 차원에서 크기가 일치하지 않으면서 양쪽 모두 크기가 1이 아니라면 브로드캐스팅이 되지 않는다.

## 텐서 형태 반환
### 1. view 함수

In [40]:
x = torch.from_numpy(np.arange(1,13).reshape(3,2,2))
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [41]:
x.view(12)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
x.view(3, -1) # -1은 나머지가 차원에 맞춰지게 함

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [43]:
# view 함수의 결과는 텐서의 주소를 바꾸지 않음 (3,2,2) <-> (3,4)
y = x.view(3,4
)

True

In [44]:
y[0][0] = 100
y

tensor([[100,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])

In [45]:
x

tensor([[[100,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]],

        [[  9,  10],
         [ 11,  12]]])

In [46]:
x.contiguous().view(-1)
x.reshape(-1) # reshape 함수는 contiguous 함수와 view 함수를 차례로 호출

tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

순차적으로 선언된 텐서가 아닌 경우 view 함수는 오류 발생하므로 contiguous()와 함께 사용

In [48]:
x = torch.FloatTensor([[1, 2], [3, 4]])
for i in range(2):
    for j in range(2):
        print(x[i][j].data_ptr()) # 차례로 메모리 위치 불러옴

4849696768
4849696772
4849696776
4849696780


In [57]:
x.stride()

(2, 1)

In [54]:
x.view(-1) # 에러 발생하므로 contifuous 사용 필요

tensor([1., 2., 3., 4.])

### 2. squeeze 함수
차원의 크기가 1인 차원을 제거

In [59]:
x = torch.FloatTensor([[[1, 2], [3, 4]]])
x.size()

torch.Size([1, 2, 2])

In [61]:
x.squeeze()

tensor([[1., 2.],
        [3., 4.]])

### 3. unsqueeze 함수
squeeze 함수와 반대로 크기가 1인 차원을 삽입함 (삽입할 위치 지정)

In [63]:
x = torch.FloatTensor([[1, 2], [3, 4]])
x.size()

torch.Size([2, 2])

In [64]:
x.unsqueeze(1).size()

torch.Size([2, 1, 2])

In [66]:
x.unsqueeze(-1).size()

torch.Size([2, 2, 1])

In [68]:
import torch
a = torch.FloatTensor([[[1],[2],[3]],[[4],[5],[6]]]) # shape (2,3,1)
print(a)

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])


In [79]:
b = a.squeeze() # shape (2,3) -> [[1,2,3][4,5,6]]
c = b.T # shape (3,2) -> [1,4][2,5][3,6]
d = c.unsqueeze(0) # shape (1,3,2)


b.size()
c.size()
d.size()

torch.Size([1, 3, 2])

## 텐서 자르기 & 붙이기
### 1. 인덱싱과 슬라이싱

In [80]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9, 10],[11,12]]])
print(x.size())

torch.Size([3, 2, 2])


### 2. split 함수
텐서를 특정 차원에 대해서 원하는 크기로 잘라줌
원하는 크기로 나누고 마지막은 남은 것을 배분
- split_size: 나누는 조각 크기
- dim: 나누게 되는 차원

In [81]:
x = torch.FloatTensor(10,4)
splits = x.split(4, dim=0)
for s in splits:
        print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


### 3. chunk 함수
크기에 상관없이 원하는 개수로 나눔
최대한 같은 크기로 나누고 마지막에 나머지를 배분
- chunk: 나누는 조각의 개수
- dim: 나누게 되는 차원

In [83]:
x = torch.FloatTensor(10,4)
chunks = x.chunk(4, dim=0)
for c in splits:
        print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 4])


### 4. index_select 함수
특정 차원에서 원하는 인덱스 위치의 값만 가져옴 
- dim: 인덱스를 지정할 차원
- index: 정수 텐서로 지정한 인덱스 목록

In [87]:
x = torch.FloatTensor([[[1, 1],[2, 2]],[[3, 3],[4, 4]],[[5, 5],[6, 6]]])
indice = torch.LongTensor([2, 1])
y = x.index_select(dim=0, index=indice)
print(y)

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])


### 5. concatenate 함수
여러 텐서를 합쳐서 하나의 텐서를 생성
- tensors: 텐서 목록
- dim: int, optional

In [89]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])
print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [90]:
z = torch.cat([x,y], dim=0)
print(z)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])


### 6. stack 함수
cat() 함수와 비슷하지만 새로운 차원을 추가하여 합치는 텐서를 쌓는 방식으로 합침

In [91]:
z = torch.stack([x,y])
print(z)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])


## 유용한 함수들
### 1. expand 함수
차원의 크기가 차원을 원하는 크기로 늘려줌

In [92]:
x = torch.FloatTensor([[[1,2]],[[3,4]]])
x.size()

torch.Size([2, 1, 2])

In [93]:
y = x.expand(2,3,2)
print(y)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


### 2. random permutation 함수
인수로 주어진 숫자로, 0부터 해당 숫자 앞가지의 정수를 임의의 순서로 텐서를 만듦   
suffle()은 주어진 데이터를 섞는 것이고, randperm()은 1부터 해당 숫자까지 데이터를 생성해서 섞는 것이 다름   
딥러닝 학습에서 데이터를 무작 순서로 넣어주기 위해 데이터의 인덱스를 섞어주는 역할로 사용 (데이터 크기 일치)

In [94]:
x = torch.randperm(10)
x

tensor([8, 0, 2, 9, 4, 7, 3, 1, 5, 6])

### 3. argument max 함수
X의 원소 중에서 함수 f(x)의 출력값을 최대로 하는 입력 x를 반환   
즉, 함수 f(x)의 최대값이 나오는 텐서 X의 인덱스를 반환

In [96]:
x = torch.randperm(3**3).reshape(3,3,-1)
x

tensor([[[16, 10, 17],
         [ 4, 21, 15],
         [19,  3,  0]],

        [[26, 14,  6],
         [11, 20, 18],
         [ 7,  5, 25]],

        [[23,  2,  1],
         [22, 13, 24],
         [ 9,  8, 12]]])

In [97]:
x.argmax(dim=-1) #가장 큰 숫자가 있는 위치를 출력 -> 3차원이 2차원으로 변환(차원이 하나 감소)

tensor([[2, 1, 0],
        [0, 1, 2],
        [0, 2, 2]])

결과 텐서의 첫번째 1은 [21,25,4] 중에서 제일 큰 인덱스 1을 의미함

### 4. top-k 함수
argmax() 함수는 가장 큰 값의 인덱스를 반환하는 것에 반해, topx() 함수는 가장 큰 값부터 k개의 값과 인덱스를 모두 반환   
따라서 k=1일 때도 argmax()보다 차원이 하나 더 늘어남

In [98]:
values, indices = torch.topk(x, k=1, dim=-1)

print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


In [99]:
print(values)
print(indices)

tensor([[[17],
         [21],
         [19]],

        [[26],
         [20],
         [25]],

        [[23],
         [24],
         [12]]])
tensor([[[2],
         [1],
         [0]],

        [[0],
         [1],
         [2]],

        [[0],
         [2],
         [2]]])


### 5. sort 함수
텐서 x를 원하는 차원 기준으로 정렬 후 k개를 뽑아오는 파이토치 코드